# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-21 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import userprofile.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.FileField(default='null', upload_to=userprofile.models.user_directory_path),
            preserve_default=False,
        ),
    ]
