# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 18:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('instrument', models.CharField(choices=[('DRUMS', 'Drums'), ('KEYBOARD', 'Keyboard'), ('GUITAR', 'Guitar'), ('VIOLIN', 'Violin')], default='GUITAR', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, default='', max_length=200)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances_added', to=settings.AUTH_USER_MODEL)),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musicians_spotted', to='app.Musician')),
            ],
            options={
                'ordering': ('date_time',),
            },
        ),
    ]
