# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 18:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_musician_associated_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='associated_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='performance',
            name='musician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='app.Musician'),
        ),
    ]
