# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-21 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170521_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
